apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 746669194487.dkr.ecr.us-east-2.amazonaws.com/myapp:latest
        ports:
        - containerPort: 80
